### ISSUE TITLE
panic: runtime error: slice bounds out of range [:4] with capacity 0

### ISSUE THREAD

**Issue by joe-at-startupmedia** [joe-at-startupmedia/golang-ipc#1]
The following error happens, it seems to occur when subsequent server read requests happen to close to one another.
```
panic: runtime error: slice bounds out of range [:4] with capacity 0

goroutine 39 [running]:
github.com/joe-at-startupmedia/golang-ipc.(*Server).read(0xc000208d90)
	/root/go/pkg/mod/github.com/joe-at-startupmedia/golang-ipc@v1.2.5/server_all.go:132 +0x33c
created by github.com/joe-at-startupmedia/golang-ipc.(*Server).acceptLoop in goroutine 11
	/root/go/pkg/mod/github.com/joe-at-startupmedia/golang-ipc@v1.2.5/server_all.go:81 +0x14c
```

At the very least the server should gracefully exit and allow a restart

**Comment by joe-at-startupmedia** [comment]
unable to replicate this in the latest iterations of development.
